name: CI/CD Pipeline

on:
  workflow_dispatch: 
    inputs:
      environment: 
        type: environment
        required: true

jobs:
  build:
    environment: "${{ inputs.environment }}"
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v2

     
      - run: echo "Die Environment ist ${{inputs.environment }}"
      - run: echo "Der wert Environmentvariable description ist ${{ vars.DESCRIPTION }}"
      - run: echo "mein benutzer-secret ist ${{ secrets.MONGODB_USERNAME }}"
      
      - run: |
         echo "SECRET_API_KEY=$SECRET_API_KEY" >> $GITHUB_ENV
